stages:
- test

run_test:
  stage: test
  script:
    - python run_tests.py

tad_tester:
  stage: test
  script:
    - python -m scripts.tad_tester --no-ebd --no-verbose # TODO: remove --no-ebd once that works

